# Generated by Django 6.0 on 2026-01-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cliques',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='whatsapp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
