# Generated by Django 6.0 on 2026-01-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_categoria_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem',
            field=models.TextField(max_length=255),
        ),
    ]
